sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull eosio/eos:latest
- docker volume create --name=nodeos-data-volume
- docker volume create --name=keosd-data-volume
- docker-compose -f docker-compose.yaml up -d
- curl http://127.0.0.1:8888/v1/chain/get_info
- cp config.json.ci config.json
- sudo apt-get install -y jq bc

script:
- pwd
- ls -lah
- sudo ./start.sh